const drizzleOrm = require('drizzle-orm');

const DATABASE = Symbol.for('WORKSPACE_OS.DATABASE');

module.exports = {
  DATABASE,
  db: {},
  sql: drizzleOrm.sql,
  eq: drizzleOrm.eq,
  ne: drizzleOrm.ne,
  and: drizzleOrm.and,
  or: drizzleOrm.or,
  not: drizzleOrm.not,
  gt: drizzleOrm.gt,
  gte: drizzleOrm.gte,
  lt: drizzleOrm.lt,
  lte: drizzleOrm.lte,
  isNull: drizzleOrm.isNull,
  isNotNull: drizzleOrm.isNotNull,
  like: drizzleOrm.like,
  ilike: drizzleOrm.ilike,
  inArray: drizzleOrm.inArray,
  notInArray: drizzleOrm.notInArray,
  exists: drizzleOrm.exists,
  notExists: drizzleOrm.notExists,
  asc: drizzleOrm.asc,
  desc: drizzleOrm.desc,
  between: drizzleOrm.between,
  WORKSPACE_ROLE_RANK: { VIEWER: 0, EDITOR: 1, ADMIN: 2, OWNER: 3 },
  WORKSPACE_SLUG_PATTERN: /^[a-z0-9](?:[a-z0-9-]{0,30}[a-z0-9])?$/,
  WORKSPACE_SLUG_MAX_LENGTH: 32,
  WORKSPACE_NAME_MIN_LENGTH: 1,
  WORKSPACE_NAME_MAX_LENGTH: 100,
  MAX_PENDING_INVITATIONS_PER_WORKSPACE: 50,
  users: { id: 'users.id' },
  workspaces: { id: 'workspaces.id' },
  workspaceMembers: { id: 'workspaceMembers.id' },
  invitations: { id: 'invitations.id' },
  UserStatus: { ACTIVE: 'ACTIVE', SUSPENDED: 'SUSPENDED', DELETED: 'DELETED' },
  WorkspaceStatus: { ACTIVE: 'ACTIVE', ARCHIVED: 'ARCHIVED', DELETED: 'DELETED' },
  WorkspaceRole: { VIEWER: 'VIEWER', EDITOR: 'EDITOR', ADMIN: 'ADMIN', OWNER: 'OWNER' },
  InvitationStatus: { PENDING: 'PENDING', ACCEPTED: 'ACCEPTED', REVOKED: 'REVOKED', EXPIRED: 'EXPIRED' },
};
