const drizzleOrm = require('drizzle-orm');

const DATABASE = Symbol.for('WORKSPACE_OS.DATABASE');

module.exports = {
  DATABASE,
  db: {},
  sql: drizzleOrm.sql,
  eq: drizzleOrm.eq,
  ne: drizzleOrm.ne,
  and: drizzleOrm.and,
  or: drizzleOrm.or,
  not: drizzleOrm.not,
  gt: drizzleOrm.gt,
  gte: drizzleOrm.gte,
  lt: drizzleOrm.lt,
  lte: drizzleOrm.lte,
  isNull: drizzleOrm.isNull,
  isNotNull: drizzleOrm.isNotNull,
  like: drizzleOrm.like,
  ilike: drizzleOrm.ilike,
  inArray: drizzleOrm.inArray,
  notInArray: drizzleOrm.notInArray,
  exists: drizzleOrm.exists,
  notExists: drizzleOrm.notExists,
  asc: drizzleOrm.asc,
  desc: drizzleOrm.desc,
  between: drizzleOrm.between,
  WORKSPACE_ROLE_RANK: { VIEWER: 0, EDITOR: 1, ADMIN: 2, OWNER: 3 },
  WORKSPACE_SLUG_PATTERN: /^[a-z0-9](?:[a-z0-9-]{0,30}[a-z0-9])?$/,
  WORKSPACE_SLUG_MAX_LENGTH: 32,
  WORKSPACE_NAME_MIN_LENGTH: 1,
  WORKSPACE_NAME_MAX_LENGTH: 100,
  MAX_PENDING_INVITATIONS_PER_WORKSPACE: 50,
  users: { id: 'users.id' },
  sessions: { id: 'sessions.id' },
  workspaces: { id: 'workspaces.id' },
  workspaceMembers: { id: 'workspaceMembers.id' },
  invitations: { id: 'invitations.id' },
  boards: { id: 'boards.id' },
  boardColumns: { id: 'boardColumns.id' },
  tasks: { id: 'tasks.id' },
  BOARD_NAME_MIN_LENGTH: 1,
  BOARD_NAME_MAX_LENGTH: 128,
  COLUMN_NAME_MIN_LENGTH: 1,
  COLUMN_NAME_MAX_LENGTH: 64,
  UserStatus: { ACTIVE: 'ACTIVE', SUSPENDED: 'SUSPENDED', DELETED: 'DELETED' },
  WorkspaceStatus: { ACTIVE: 'ACTIVE', ARCHIVED: 'ARCHIVED', DELETED: 'DELETED' },
  WorkspaceRole: { VIEWER: 'VIEWER', EDITOR: 'EDITOR', ADMIN: 'ADMIN', OWNER: 'OWNER' },
  InvitationStatus: { PENDING: 'PENDING', ACCEPTED: 'ACCEPTED', REVOKED: 'REVOKED', EXPIRED: 'EXPIRED' },
  BoardStatus: { ACTIVE: 'ACTIVE', ARCHIVED: 'ARCHIVED' },
  boardComments: { id: 'boardComments.id' },
  notifications: { id: 'notifications.id' },
  identities: { id: 'identities.id' },
  emailVerificationTokens: { id: 'emailVerificationTokens.id' },
  passwordResetTokens: { id: 'passwordResetTokens.id' },
  pushSubscriptions: { id: 'pushSubscriptions.id' },
  canvas: { id: 'canvas.id' },
  canvasObjects: { id: 'canvasObjects.id' },
  uploadedFiles: { id: 'uploadedFiles.id' },
  auditEvents: { id: 'auditEvents.id' },
  checklistItems: { id: 'checklistItems.id' },
  NotificationStatus: { CREATED: 'CREATED', QUEUED: 'QUEUED', DELIVERED: 'DELIVERED', READ: 'READ', ARCHIVED: 'ARCHIVED' },
  NotificationType: { COMMENT_ADDED: 'COMMENT_ADDED', BOARD_SHARED: 'BOARD_SHARED', WORKSPACE_UPDATED: 'WORKSPACE_UPDATED', MENTION_CREATED: 'MENTION_CREATED', MEMBER_ADDED: 'MEMBER_ADDED', INVITATION_ACCEPTED: 'INVITATION_ACCEPTED', TASK_ASSIGNED: 'TASK_ASSIGNED' },
  notificationTypeEnum: {
    enumValues: [
      'COMMENT_ADDED',
      'BOARD_SHARED',
      'WORKSPACE_UPDATED',
      'MENTION_CREATED',
      'MEMBER_ADDED',
      'INVITATION_ACCEPTED',
      'TASK_ASSIGNED',
      'TASK_UNASSIGNED',
      'TASK_DELETED',
      'FILE_UPLOADED',
    ],
  },
  COMMENT_CONTENT_MIN_LENGTH: 1,
  TASK_TITLE_MIN_LENGTH: 1,
  TASK_TITLE_MAX_LENGTH: 256,
  TaskStatus: { BACKLOG: 'BACKLOG', TODO: 'TODO', IN_PROGRESS: 'IN_PROGRESS', IN_REVIEW: 'IN_REVIEW', DONE: 'DONE', CANCELLED: 'CANCELLED' },
  TaskPriority: { NONE: 'NONE', LOW: 'LOW', MEDIUM: 'MEDIUM', HIGH: 'HIGH', CRITICAL: 'CRITICAL' },
};
